import { marked } from 'marked';

export async function renderResearchHtml(ticker: string, reportText: string): Promise<Buffer> {
  // Convert standard markdown to HTML
  const contentHtml = await marked(reportText);

  const html = `<!DOCTYPE html>
<html lang="zh-TW">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${ticker} 深度研調報告</title>
  <style>
    :root {
      --bg-color: #0f101a;
      --card-bg: #1a1c2c;
      --text-main: #e2e8f0;
      --text-muted: #94a3b8;
      --accent: #60a5fa;
      --border: #334155;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      background-color: var(--bg-color);
      color: var(--text-main);
      line-height: 1.6;
      padding: 20px;
      margin: 0;
    }
    .container {
      max-width: 800px;
      margin: 0 auto;
      background-color: var(--card-bg);
      border-radius: 12px;
      padding: 30px;
      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.5);
      border: 1px solid var(--border);
    }
    h1, h2, h3 {
      color: var(--accent);
      margin-top: 1.5em;
      margin-bottom: 0.5em;
    }
    h1 {
      font-size: 2rem;
      border-bottom: 2px solid var(--border);
      padding-bottom: 10px;
      margin-top: 0;
    }
    p, li {
      margin-bottom: 1em;
      font-size: 1.05rem;
    }
    a {
      color: var(--accent);
      text-decoration: none;
    }
    a:hover {
      text-decoration: underline;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid var(--border);
      font-size: 0.85rem;
      color: var(--text-muted);
      text-align: center;
    }
    ul, ol {
      padding-left: 20px;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>🔍 ${ticker} 深度研調報告</h1>
    <p style="color: var(--text-muted); font-size: 0.9rem;">Generated by DeepMind AI Assistant • 30 Days Sentiment Analysis</p>
    
    <div class="content">
      ${contentHtml}
    </div>

    <div class="footer">
      此報告由 AI (混合 last30days-skill) 分析生成，僅供參考，不構成投資建議。
    </div>
  </div>
</body>
</html>`;

  return Buffer.from(html, 'utf-8');
}
