import { createCanvas } from '@napi-rs/canvas';
import { NOTO_SANS_BOLD_B64 } from './fontData';
import * as opentype from 'opentype.js';

let _otFont: opentype.Font | null = null;
function getOtFont() {
  if (_otFont) return _otFont;
  try {
    const buf = Buffer.from(NOTO_SANS_BOLD_B64, 'base64');
    _otFont = opentype.parse(buf.buffer);
    return _otFont;
  } catch (e) {
    console.error('Failed to parse embedded font with opentype:', e);
    return null;
  }
}

function wrapText(ctx: any, text: string, maxWidth: number) {
  const words = text.split('');
  const lines = [];
  let currentLine = '';

  for (let i = 0; i < words.length; i++) {
    const word = words[i];
    const width = ctx.measureText(currentLine + word).width;
    if (width < maxWidth) {
      currentLine += word;
    } else {
      lines.push(currentLine);
      currentLine = word;
    }
  }
  lines.push(currentLine);
  return lines;
}

export async function renderResearchImage(ticker: string, reportText: string): Promise<Buffer> {
  const width = 800;
  // 先粗略計算高度
  const tempCanvas = createCanvas(width, 100);
  const tempCtx = tempCanvas.getContext('2d');
  tempCtx.font = '20px sans-serif'; // Fallback font for measurement
  
  // 移除 HTML 標籤以便計算
  const plainText = reportText.replace(/<[^>]+>/g, '').replace(/&amp;/g, '&');
  const sections = plainText.split('\n');
  let totalHeight = 150; // Header height
  
  const wrappedLines: string[][] = [];
  for (const s of sections) {
    const lines = wrapText(tempCtx, s, width - 80);
    wrappedLines.push(lines);
    totalHeight += lines.length * 30 + 10;
  }
  totalHeight += 50; // Padding

  const canvas = createCanvas(width, totalHeight);
  const ctx = canvas.getContext('2d');

  // 背景
  const gradient = ctx.createLinearGradient(0, 0, 0, totalHeight);
  gradient.addColorStop(0, '#1a1c2c');
  gradient.addColorStop(1, '#0f101a');
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, width, totalHeight);

  // 浮水印
  ctx.save();
  ctx.font = 'bold 150px sans-serif';
  ctx.fillStyle = 'rgba(255, 255, 255, 0.03)';
  ctx.textAlign = 'center';
  ctx.translate(width / 2, totalHeight / 2);
  ctx.rotate(-Math.PI / 4);
  ctx.fillText(ticker, 0, 0);
  ctx.restore();

  // 標題裝飾
  ctx.fillStyle = '#4e54c8';
  ctx.fillRect(0, 0, width, 5);
  
  ctx.fillStyle = '#ffffff';
  ctx.font = 'bold 36px sans-serif';
  ctx.fillText(`🔍 ${ticker} 深度研調報告`, 40, 70);
  
  ctx.font = '16px sans-serif';
  ctx.fillStyle = '#888888';
  ctx.fillText(`Generated by DeepMind AI Assistant • 30 Days Sentiment Analysis`, 40, 100);

  // 內容繪製
  let y = 150;
  for (const lines of wrappedLines) {
    for (const line of lines) {
      if (line.trim().match(/^[0-9]\. /) || line.includes('**')) {
        ctx.fillStyle = '#a8b2ff';
        ctx.font = 'bold 22px sans-serif';
      } else {
        ctx.fillStyle = '#d1d1d1';
        ctx.font = '20px sans-serif';
      }
      ctx.fillText(line, 40, y);
      y += 30;
    }
    y += 10;
  }

  // 頁尾
  ctx.strokeStyle = '#333333';
  ctx.beginPath();
  ctx.moveTo(40, totalHeight - 40);
  ctx.lineTo(width - 40, totalHeight - 40);
  ctx.stroke();
  
  ctx.font = 'italic 14px sans-serif';
  ctx.fillStyle = '#555555';
  ctx.fillText('此報告由 AI 檢索並生成，僅供參考，不構成投資建議。', 40, totalHeight - 20);

  return canvas.toBuffer('image/png');
}
